namespace ToStringSourceGenerator.Tests;

public sealed partial class ToStringIncrementalSourceGeneratorTests
{
    private const string ClassName = "SampleEntity";

    private const string ClassText = @$"
namespace TestNamespace;

[Generators.ToString]
public partial class {ClassName}
{{
    public SampleEntity(string? text, int number, SampleEntity? entity)
    {{
        Text = text;
        Number = number;
        Entity = entity;
    }}

    public string? Text {{ get; }}
    public int Number {{ get; }}
    public SampleEntity? Entity {{ get; }}
}}";

    private const string ExpectedGeneratedClassText = @$"// <auto-generated/>

using System;
using System.Collections.Generic;

namespace TestNamespace;

public partial class {ClassName}
{{
    public override string ToString()
    {{
        return $""SampleEntity {{{{ Text = {{this.Text}}, Number = {{this.Number}}, Entity = {{this.Entity?.ToString()}} }}}}"";
    }}
}}
";
}
